context:
  version: "0.16.4"

package:
  name: libid3tag
  version: ${{ version }}

source:
  url: https://codeberg.org/tenacityteam/libid3tag/archive/${{ version }}.tar.gz
  sha256: ceb88ada1aa867c87c1d748a8aa40e68db5b0d2df636a9dab0ab1f7741d5e009

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - if: unix
      then: gperf
      else: m2-gperf
  host:
    - zlib
  run_exports:
    - ${{ pin_subpackage('libid3tag') }}

tests:
  - script:
      - if: unix
        then:
          - test -f ${PREFIX}/lib/libid3tag${SHLIB_EXT}
        else:
          - if not exist %LIBRARY_PREFIX%\lib\id3tag.lib exit 1
          - if not exist %LIBRARY_PREFIX%\bin\id3tag.dll exit 1

about:
  license: GPL-2.0-only
  license_file: COPYING
  summary: ID3 tag manipulation library
  homepage: https://www.underbit.com/products/mad/
  repository: https://codeberg.org/tenacityteam/libid3tag

extra:
  recipe-maintainers:
    - danielnachun
